# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_superfastgsea_wrappers", use_symbols = TRUE, package_name = "superfastgsea")

#' @docType package
#' @usage NULL
#' @useDynLib superfastgsea, .registration = TRUE
NULL

#' Test function to verify Rust-R bridge works
#' @export
rust_hello <- function() {
    .Call(wrap__rust_hello, PACKAGE = "superfastgsea")
}

#' Calculate enrichment score for a single gene set
#' @param stats Named numeric vector of gene statistics (sorted by stat value)
#' @param gene_set_indices Integer vector of indices (1-based) for genes in the set
#' @param gsea_param Weighting parameter for gene statistics (default 1.0)
#' @return List containing ES, NES estimate, and leading edge indices
#' @export
calc_es_rust <- function(stats, gene_set_indices, gsea_param) {
    .Call(wrap__calc_es_rust, stats, gene_set_indices, gsea_param, PACKAGE = "superfastgsea")
}

#' Run GSEA analysis on multiple pathways in parallel
#' @param stats Named numeric vector of gene statistics
#' @param pathway_indices List of integer vectors, each containing gene indices for a pathway
#' @param pathway_names Character vector of pathway names
#' @param gsea_param Weighting parameter (default 1.0)
#' @param n_anchors Number of anchor samples for Gamma fitting (default 200)
#' @param min_size Minimum pathway size (default 1)
#' @param max_size Maximum pathway size (default Inf)
#' @param score_type Score type: "std", "pos", or "neg" (default "std")
#' @return Data frame with GSEA results
#' @export
run_gsea_rust <- function(stats, pathway_indices, pathway_names, gsea_param, n_anchors, min_size, max_size, score_type) {
    .Call(wrap__run_gsea_rust, stats, pathway_indices, pathway_names, gsea_param, n_anchors, min_size, max_size, score_type, PACKAGE = "superfastgsea")
}

#' Run GSEA analysis with method selection
#' @param stats Named numeric vector of gene statistics
#' @param pathway_indices List of integer vectors, each containing gene indices for a pathway
#' @param pathway_names Character vector of pathway names
#' @param gsea_param Weighting parameter (default 1.0)
#' @param n_anchors Number of anchor samples (default: 200 for gamma, 500 for gpd)
#' @param min_size Minimum pathway size (default 1)
#' @param max_size Maximum pathway size (default Inf)
#' @param score_type Score type: "std", "pos", or "neg" (default "std")
#' @param method Method for p-value estimation: "gamma" or "empirical_gpd" (default "gamma")
#' @return Data frame with GSEA results
#' @export
run_gsea_rust_with_method <- function(stats, pathway_indices, pathway_names, gsea_param, n_anchors, min_size, max_size, score_type, method) {
    .Call(wrap__run_gsea_rust_with_method, stats, pathway_indices, pathway_names, gsea_param, n_anchors, min_size, max_size, score_type, method, PACKAGE = "superfastgsea")
}

#' Run GSEA analysis with adaptive sampling
#' @param stats Named numeric vector of gene statistics
#' @param pathway_indices List of integer vectors, each containing gene indices for a pathway
#' @param pathway_names Character vector of pathway names
#' @param gsea_param Weighting parameter (default 1.0)
#' @param min_size Minimum pathway size (default 1)
#' @param max_size Maximum pathway size (default Inf)
#' @param score_type Score type: "std", "pos", or "neg" (default "std")
#' @return List with GSEA results and total_samples_used
#' @export
run_gsea_rust_adaptive <- function(stats, pathway_indices, pathway_names, gsea_param, min_size, max_size, score_type) {
    .Call(wrap__run_gsea_rust_adaptive, stats, pathway_indices, pathway_names, gsea_param, min_size, max_size, score_type, PACKAGE = "superfastgsea")
}

#' Run GSEA with two-pass coarse-to-fine strategy
#' @param stats Named numeric vector of gene statistics
#' @param pathway_indices List of integer vectors
#' @param pathway_names Character vector of pathway names
#' @param gsea_param Weighting parameter (default 1.0)
#' @param min_size Minimum pathway size (default 1)
#' @param max_size Maximum pathway size (default Inf)
#' @param score_type Score type: "std", "pos", or "neg" (default "std")
#' @param coarse_anchors Anchors for coarse pass (default 50)
#' @param fine_anchors Anchors for fine pass (default 200)
#' @param pvalue_threshold P-value threshold for fine pass (default 0.2)
#' @return List with GSEA results and pass statistics
#' @export
run_gsea_rust_two_pass <- function(stats, pathway_indices, pathway_names, gsea_param, min_size, max_size, score_type, coarse_anchors, fine_anchors, pvalue_threshold) {
    .Call(wrap__run_gsea_rust_two_pass, stats, pathway_indices, pathway_names, gsea_param, min_size, max_size, score_type, coarse_anchors, fine_anchors, pvalue_threshold, PACKAGE = "superfastgsea")
}

#' Run GSEA with batch optimization (shared samples + vectorized ES)
#' @param stats Named numeric vector of gene statistics
#' @param pathway_indices List of integer vectors
#' @param pathway_names Character vector of pathway names
#' @param gsea_param Weighting parameter (default 1.0)
#' @param n_anchors Number of anchor samples (default 200)
#' @param min_size Minimum pathway size (default 1)
#' @param max_size Maximum pathway size (default Inf)
#' @param score_type Score type: "std", "pos", or "neg" (default "std")
#' @return Data frame with GSEA results
#' @export
run_gsea_rust_batch <- function(stats, pathway_indices, pathway_names, gsea_param, n_anchors, min_size, max_size, score_type) {
    .Call(wrap__run_gsea_rust_batch, stats, pathway_indices, pathway_names, gsea_param, n_anchors, min_size, max_size, score_type, PACKAGE = "superfastgsea")
}
